version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dotnet-api-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Postgres=Host=postgres-db-service;Port=5432;Database=postgres;Username=postgres;Password=postgres;Timeout=30
    ports:
      - "5000:8080"
    depends_on:
      database:
         condition: service_healthy
    networks:
      - keyvalue-network
    command: ["./wait-for-it.sh", "postgres-db-service:5432", "--", "dotnet", "DotnetMinimalApi.dll"]


  database:
    image: postgres:latest
    container_name: postgres-db-service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - keyvalue-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  keyvalue-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
